### ISSUE TITLE
Decoding error 

### ISSUE THREAD

**Issue by andrebola** [sertansenturk/tomato#64]
I saw this error for the file: haci_arif_bey/05_-_tanbur_taksimi.mp3

[2016-06-02 13:07:29,113: ERROR/MainProcess] Task docserver.jobs.process_document[0f8bf99c-e242-4dbd-953d-1c1833bd9e30] raised unexpected: UnicodeDecodeError('ascii', '/incoming/Turkey-makam/audio/Me\xc5\x9fk-i Safa/19 D\xc3\xbc\xc5\x9fer mi \xc5\x9e\xc3\xa2n\xc4\xb1na Ey \xc5\x9eeh-i H\xc3\xbbb\xc3\xa2n (K\xc3\xbcrdilihicazk\xc3\xa2r \xc5\x9eark\xc4\xb1).mp3', 31, 32, 'ordinal not in range(128)')
Traceback (most recent call last):
  File "/srv/dunya/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/srv/dunya/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/srv/dunya/docserver/jobs.py", line 325, in process_document
    results = instance.process_document(document.pk, s.pk, document.external_identifier, fname)
  File "/srv/dunya/env/src/pycompmusic/compmusic/extractors/__init__.py", line 137, in process_document
    return self.run(musicbrainzid, fname)
  File "/srv/dunya/env/src/pycompmusic/compmusic/extractors/makam/audioanalysis.py", line 53, in run
    features = audioAnalyzer.analyze(fname)
  File "/srv/dunya/env/src/tomato/tomato/audio/audioanalyzer.py", line 57, in analyze
    filepath)
  File "/srv/dunya/env/src/tomato/tomato/audio/audioanalyzer.py", line 116, in _call_audio_metadata
    filepath)
  File "/srv/dunya/env/src/tomato/tomato/audio/audioanalyzer.py", line 142, in crawl_musicbrainz_metadata
    self.vprint(u"- Getting relevant metadata of {0:s}".format(rec_in))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 31: ordinal not in range(128)

**Comment by sertansenturk** [comment]
I cannot reproduce it in my Linux machine. Can you tell me what `rec_in` is?

**Comment by andrebola** [comment]
sorry, this is the file:

Meşk-i Safa/19 Düşer mi Şânına Ey Şeh-i Hûbân (Kürdilihicazkâr Şarkı).mp3

**Comment by sertansenturk** [comment]
so the input is u'19 Düşer mi Şânına Ey Şeh-i Hûbân (Kürdilihicazkâr Şarkı).mp3' instead of '19 Düşer mi Şânına Ey Şeh-i Hûbân (Kürdilihicazkâr Şarkı).mp3' the analyzer works fine. 

I'm not sure if I should check/correct the encoding inside the module or not? What is your opiniion?

**Comment by sertansenturk** [comment]
I think the last commit solves the issue, can you confirm?

**Comment by andrebola** [comment]
Yes, it's fixed
