### ISSUE TITLE
non asci characters on joint analysis

### ISSUE THREAD

**Issue by andrebola** [sertansenturk/tomato#66]
For the joint analysis I;m getting this error:

[2016-06-07 22:28:18,235: ERROR/MainProcess] Task docserver.jobs.process_document[ec3eb674-913b-4af6-b267-0caa72a5f26d] raised unexpected: UnicodeEncodeError('ascii', u'/incoming/Turkey-makam/audio/ZekiMuren1955_1963Kayitlari1/1-17 Acemk\xfcrdi Pe\u015frev (1. Hane - Teslim).mp3', 68, 69, 'ordinal not in range(128)')
Traceback (most recent call last):
  File "/srv/dunya/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/srv/dunya/env/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/srv/dunya/docserver/jobs.py", line 325, in process_document
    results = instance.process_document(document.pk, s.pk, document.external_identifier, fname)
  File "/srv/dunya/env/src/pycompmusic/compmusic/extractors/__init__.py", line 137, in process_document
    return self.run(musicbrainzid, fname)
  File "/srv/dunya/env/src/pycompmusic/compmusic/extractors/makam/jointanalysis.py", line 96, in run
    symbtr_file, score_features, fname, audio_pitch)
  File "/srv/dunya/env/src/tomato/tomato/joint/jointanalyzer.py", line 51, in analyze
    audio_pitch)
  File "/srv/dunya/env/src/tomato/tomato/joint/jointanalyzer.py", line 175, in extract_tonic_tempo
    audio_filename, temp_pitch_file, temp_out_folder)]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 68: ordinal not in range(128)

**Comment by sertansenturk** [comment]
It was due to the "callstr" inputs not specified as unicode.
