### ISSUE TITLE
pitchfilter error

### ISSUE THREAD

**Issue by andrebola** [sertansenturk/tomato#67]
File:
Ferahnak Yürüksemai 
9d26b16c-4d91-4949-9412-b638a93111d9

Traceback (most recent call last):
  File "/srv/dunya/env/src/pycompmusic/compmusic/extractors/__init__.py", line 137, in process_document
    return self.run(musicbrainzid, fname)
  File "/srv/dunya/env/src/pycompmusic/compmusic/extractors/makam/audioanalysis.py", line 53, in run
    features = audioAnalyzer.analyze(fname)
  File "/srv/dunya/env/src/tomato/tomato/audio/audioanalyzer.py", line 77, in analyze
    audio_f['tonic'], self.identify_tonic, audio_f['pitch_filtered'])
  File "/srv/dunya/env/src/tomato/tomato/analyzer.py", line 62, in _partial_caller
    return func(*input_args, **input_kwargs)
  File "/srv/dunya/env/src/tomato/tomato/audio/audioanalyzer.py", line 215, in identify_tonic
    tonic = self._tonic_identifier.identify(pitch['pitch'])[0]
  File "/srv/dunya/env/local/lib/python2.7/site-packages/tonicidentifier/toniclastnote.py", line 70, in identify
    pitch_chunks = flt.post_filter_chunks(pitch_chunks)
  File "/srv/dunya/env/local/lib/python2.7/site-packages/pitchfilter/pitchfilter.py", line 32, in post_filter_chunks
    if len(pitch_chunks[i]) <= self.min_chunk_size]
TypeError: object of type 'numpy.float64' has no len()

**Comment by sertansenturk** [comment]
It was due to a rare error where pitch filter tried to remove bad chunks even when there is no such chunk. Pitchfilter is updated, so you should reinstall tomato.

**Comment by sertansenturk** [comment]
@andrebola  is this fixed?

**Comment by andrebola** [comment]
This is working now:
http://dunya.compmusic.upf.edu/document/by-id/9d26b16c-4d91-4949-9412-b638a93111d9/jointanalysis?v=0.1&subtype=pitch

**Comment by sertansenturk** [comment]
Cool! In the meantime but why can't we see the melodic progression, spectrogram and the predominant melody? http://dunya.compmusic.upf.edu/makam/recording/9d26b16c-4d91-4949-9412-b638a93111d9

If it's not related to tomato but Dunya I'll close the issue

**Comment by andrebola** [comment]
The image wasn't generated, now is working!
