### ISSUE TITLE
ahenkidentifier error 

### ISSUE THREAD

**Issue by andrebola** [sertansenturk/tomato#68]
File:

Ferahfezâ Son Taksim (âyinden)
13e1f926-4b77-4a06-98eb-0b4593b6ea7a                

Traceback (most recent call last):
  File "/srv/dunya/env/src/pycompmusic/compmusic/extractors/__init__.py", line 137, in process_document
    return self.run(musicbrainzid, fname)
  File "/srv/dunya/env/src/pycompmusic/compmusic/extractors/makam/audioanalysis.py", line 53, in run
    features = audioAnalyzer.analyze(fname)
  File "/srv/dunya/env/src/tomato/tomato/audio/audioanalyzer.py", line 102, in analyze
    audio_f['tonic'], audio_f['makam'])
  File "/srv/dunya/env/src/tomato/tomato/analyzer.py", line 62, in _partial_caller
    return func(*input_args, **input_kwargs)
  File "/srv/dunya/env/src/tomato/tomato/audio/audioanalyzer.py", line 264, in identify_transposition
    tonic['value'], makam_tonic_str)
  File "/srv/dunya/env/local/lib/python2.7/site-packages/ahenkidentifier/ahenkidentifier.py", line 28, in identify
    mod_cent_approx = int(np.round(mod_cent_dist * 0.01) * 100)
TypeError: only length-1 arrays can be converted to Python scalars

**Comment by sertansenturk** [comment]
In this file tonic identification fails and hence ahenk identification.

The partial analysis method seems to handle this bug in the last version of tomato. Can you confirm?

**Comment by sertansenturk** [comment]
@andrebola is this fixed?

**Comment by sertansenturk** [comment]
Andres has confirmed that analysis works partially. Tonic is not computed because there are speed (and hence pitch) shifts in the recording so the algorithm cannot find the stable pitches properly. This causes the algorithm not to be confident with the last note's pitch and output a None. There is nothing to fix there conceptually...
